/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Automation.api.app;

import Automation.api.list.LinkedList;

import static Automation.api.utilities.StringUtils.join;
import static Automation.api.utilities.StringUtils.split;
import static Automation.api.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
